-- Sada-e-Ishq final security/realtime hardening
REVOKE EXECUTE ON FUNCTION public.admin_set_approval(bigint, uuid, public.approval_status, boolean) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.artist_my_programs() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.artist_program_detail(bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.availability_summary(bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.cancel_program(bigint, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.capture_program_backup() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.confirm_program(bigint, boolean, boolean, boolean) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.delete_program(bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.dispatch_reminders() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_active_artist() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.next_program_code() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.restore_program(bigint) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.save_and_confirm_program(jsonb, integer, boolean, boolean, boolean) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.save_program(jsonb, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.set_my_availability(bigint, public.availability_status) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.update_my_profile(text, boolean) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.audit_program_changes() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.audit_vnext_program() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.programs_touch() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.set_program_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_profile_timestamp() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.effective_status(public.programs) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_approval(bigint, uuid, public.approval_status, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.artist_my_programs() TO authenticated;
GRANT EXECUTE ON FUNCTION public.artist_program_detail(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.availability_summary(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.cancel_program(bigint, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.confirm_program(bigint, boolean, boolean, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_program(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_active_artist() TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.next_program_code() TO authenticated;
GRANT EXECUTE ON FUNCTION public.restore_program(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_and_confirm_program(jsonb, integer, boolean, boolean, boolean) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_program(jsonb, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_my_availability(bigint, public.availability_status) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_my_profile(text, boolean) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.public_upcoming_programs() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.public_upcoming_programs() TO anon, authenticated;
ALTER FUNCTION public.update_profile_timestamp() SET search_path = public;
ALTER FUNCTION public.programs_touch() SET search_path = public;
ALTER FUNCTION public.effective_status(public.programs) SET search_path = public;
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication_rel pr JOIN pg_publication p ON p.oid=pr.prpubid JOIN pg_class c ON c.oid=pr.prrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE p.pubname='supabase_realtime' AND n.nspname='public' AND c.relname='program_assignments') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.program_assignments; END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_publication_rel pr JOIN pg_publication p ON p.oid=pr.prpubid JOIN pg_class c ON c.oid=pr.prrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE p.pubname='supabase_realtime' AND n.nspname='public' AND c.relname='notifications') THEN ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications; END IF;
END $$;